class AddItem {
  final _suggestedGroceries = [
    'Apple',
    'Banana',
    'Strawberry',
    'Avocado',
    'Bell Pepper',
    'Carrot',
    'Garlic',
    'Lemon',
    'Onion',
    'Parsley',
    'Cilantro',
    'Basil',
    'Potato',
    'Spinach',
    'Tomato',
    'Bread',
    'Pasta',
    'Quinoa',
    'Rice',
    'Tortilla',
    'Chicken',
    'Eggs',
    'Ground Beef',
    'Turkey',
    'Butter',
    'Sliced Cheese',
    'Shredded Cheese',
    'Milk',
    'Sour Cream',
    'Greek Yogurt',
    'Yoghurt',
    'Baking powder',
    'Baking Soda',
    'Sugar',
    'Brown Sugar',
    'Flour',
    'Honey',
    'Vanilla',
    'Dry Yeast',
    'Chocolate Chips',
    'Cocoa Powder',
    'Powdered Sugar',
    'Corn',
    'Broccoli',
    'Pizza',
    'Stock',
    'Broth',
    'Salsa',
    'Jam',
    'Jelly',
    'Peanut Butter',
    'Pasta Sauce',
    'Black Beans',
    'Soups',
    'Tuna',
    'Chili'
  ];
}